import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

const pages = [
  "index.html",
  "product-leadership/index.html",
  "custom-builds/index.html",
  "pricing/index.html",
  "process/index.html",
  "resources/index.html",
  "faq/index.html",
  "about/index.html",
  "contact/index.html",
];

const requiredFiles = [
  ...pages,
  "robots.txt",
  "sitemap.xml",
  "llms.txt",
  "site.webmanifest",
  "assets/css/styles.css",
  "assets/js/main.js",
  "assets/img/founder-working.jpeg",
  "assets/img/founder-seated.jpeg",
  "assets/img/founder-portrait.jpeg",
  "assets/brand/logo-1a-black.png",
  "assets/brand/logo-1a-white.png",
  "assets/brand/logo-1e-black.png",
  "assets/brand/logo-1e-white.png",
  "assets/brand/mark-h-black.png",
  "assets/brand/mark-h-white.png",
  "assets/brand/wordmark-black.png",
  "assets/brand/wordmark-white.png",
  "assets/brand/icon.png",
  "assets/brand/icon-mark.png",
  "assets/brand/logo-black.png",
  "assets/brand/logo-white.png",
  "docs/design-system/Herzen-Co-logo-system.pdf",
  "docs/design-system/Logos-Herzen-Co.zip",
];

const legacyTerms = [
  ["xe", "ler", "ate"],
  ["xy", "ren"],
  ["fractional", "pm"],
].map((parts) => parts.join(""));

const retiredWebsiteOfferTerms = [
  "/conversion-websites/",
  "Conversion Websites",
  "Conversion website",
  "conversion-focused websites",
  "website support",
];

const publicExtensions = new Set([
  ".html",
  ".css",
  ".js",
  ".txt",
  ".xml",
  ".webmanifest",
  ".svg",
]);

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "content" || entry.name === "docs" || entry.name === "tests" || entry.name === "node_modules" || entry.name === "public") continue;
      out.push(...walk(full));
    } else if (publicExtensions.has(path.extname(entry.name))) {
      out.push(path.relative(root, full));
    }
  }
  return out;
}

function authoredContents(file) {
  const contents = read(file);
  if (file === "resources/index.html") {
    return contents.replace(
      /<!-- CONTENT_ENGINE_RESOURCES_START -->[\s\S]*?<!-- CONTENT_ENGINE_RESOURCES_END -->/,
      "",
    );
  }
  if (file.startsWith("resources/") && contents.includes("Generated by scripts/sync-content.mjs")) {
    return "";
  }
  return contents;
}

for (const file of requiredFiles) {
  assert(fs.existsSync(path.join(root, file)), `Missing required file: ${file}`);
}

for (const page of pages) {
  const html = read(page);
  assert(/<title>[^<]{15,70}<\/title>/i.test(html), `${page} needs a focused title tag`);
  assert(/<meta name="description" content="[^"]{50,170}"/i.test(html), `${page} needs a meta description`);
  assert(/<link rel="canonical" href="https:\/\/herzenco\.com\/[^"]*"/i.test(html), `${page} needs canonical URL`);
  assert(html.includes('/assets/css/styles.css?v=20260721content1'), `${page} should load the current shared stylesheet`);
  assert(html.includes('/assets/brand/logo-1a-black.png'), `${page} should use the approved primary logo in the header`);
  assert(html.includes('/assets/brand/logo-1a-white.png'), `${page} should use the approved reversed logo in the footer`);
  assert(!html.includes('/assets/brand/logo-black.png'), `${page} should not render the vertical black lockup`);
  assert(!html.includes('/assets/brand/logo-white.png'), `${page} should not render the vertical white lockup`);
  assert(html.includes('/assets/brand/icon.png'), `${page} should use the official icon export as the favicon`);
  assert(html.includes('/assets/js/main.js'), `${page} should load the shared site script`);
  assert(/<meta property="og:title" content="[^"]+"/i.test(html), `${page} needs OG title`);
  assert(/<meta property="og:description" content="[^"]+"/i.test(html), `${page} needs OG description`);
  assert(/<script type="application\/ld\+json">[\s\S]*?<\/script>/i.test(html), `${page} needs JSON-LD`);
  const h1Count = (html.match(/<h1[\s>]/gi) || []).length;
  assert(h1Count === 1, `${page} should have exactly one H1, found ${h1Count}`);
}

const publicFiles = walk(root);
for (const file of publicFiles) {
  const contents = authoredContents(file);
  for (const term of legacyTerms) {
    const pattern = new RegExp(term, "i");
    assert(!pattern.test(contents), `Legacy name found in ${file}: ${pattern}`);
  }

  for (const term of retiredWebsiteOfferTerms) {
    assert(!contents.includes(term), `Retired website offer found in ${file}: ${term}`);
  }
}

const homepage = read("index.html");
const packageJson = JSON.parse(read("package.json"));
const siteScript = read("assets/js/main.js");
const siteStyles = read("assets/css/styles.css");
assert(/--paper-50:\s*#f5efe4/i.test(siteStyles), "Design system should use the warm paper token");
assert(/--ink-900:\s*#1c1813/i.test(siteStyles), "Design system should use the warm ink token");
assert(/--clay-500:\s*#9c5c3e/i.test(siteStyles), "Design system should use the clay accent token");
assert(/Newsreader/.test(siteStyles) && /Jost/.test(siteStyles), "Design system should load the editorial font pairing");
assert(/messy middle/i.test(homepage), "Homepage should use the editorial studio positioning phrase: messy middle");
assert(!/Answering the questions buyers ask first/i.test(homepage), "Homepage should not use generic buyer-question section framing");
assert(/<a class="button" href="\/contact\/">Book a call<\/a>/.test(homepage), "Homepage primary CTA should collect leads through contact");
assert(!/See the primary offer/.test(homepage), "Homepage CTA should be concise and lead-focused");
assert(/editorial-hero-media/.test(homepage), "Homepage hero image should use the editorial image wrapper");
assert(/editorial-hero-media img[\s\S]*height: auto/.test(siteStyles), "Homepage hero image should not use fixed-height letterboxing");
assert(packageJson.dependencies["@vercel/analytics"], "Site should include the Vercel Analytics package");
assert(/\/_vercel\/insights\/script\.js/.test(siteScript), "Shared script should load Vercel Web Analytics");
assert(/@vercel\/analytics/.test(siteScript), "Shared script should identify the Vercel Analytics SDK");
assert(/Lead CTA Clicked/.test(siteScript), "Shared script should track lead CTA clicks");
assert(/founder-working\.jpeg/.test(homepage), "Homepage should use the founder working portrait");
assert(/founder-portrait\.jpeg/.test(read("about/index.html")), "About page should use the founder portrait");
assert(/founder-seated\.jpeg/.test(read("contact/index.html")), "Contact page should use the seated founder portrait");

const resourcesPage = read("resources/index.html");
assert(/class="resources-masthead"/.test(resourcesPage), "Resources should use the editorial masthead");
assert(/CONTENT_ENGINE_RESOURCES_START/.test(resourcesPage), "Resources should expose the Content Engine insertion point");
assert(!/What is fractional product leadership\?/.test(resourcesPage), "Resources should not contain hardcoded editorial articles");
assert(!/class="resource-row"/.test(resourcesPage), "Resources should not use the old utility-list layout");

console.log(`Verified ${pages.length} pages and ${publicFiles.length} public files.`);
