import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

const PROPERTY_SLUG = "herzenco";
const SITE_URL = "https://herzenco.com";
const GENERATED_MARKER = "<!-- Generated by scripts/sync-content.mjs. Do not edit directly. -->";

const allowedHtml = {
  allowedTags: [
    "p", "br", "strong", "em", "s", "blockquote", "ul", "ol", "li",
    "h2", "h3", "h4", "h5", "h6", "a", "code", "pre", "hr", "img",
    "figure", "figcaption", "table", "thead", "tbody", "tr", "th", "td",
  ],
  allowedAttributes: {
    a: ["href", "title"],
    img: ["src", "alt", "title", "width", "height", "loading"],
    th: ["scope"],
    td: ["colspan", "rowspan"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  allowProtocolRelative: false,
  transformTags: {
    a: (_tagName, attribs) => ({
      tagName: "a",
      attribs: {
        ...attribs,
        ...(attribs.href?.startsWith("http") ? { rel: "noopener noreferrer" } : {}),
      },
    }),
    img: (_tagName, attribs) => ({
      tagName: "img",
      attribs: { ...attribs, loading: "lazy" },
    }),
  },
};

export function escapeHtml(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function escapeXml(value = "") {
  return escapeHtml(value);
}

export function sanitizeMarkdown(markdown = "") {
  const rendered = marked.parse(String(markdown), { async: false, gfm: true });
  return sanitizeHtml(rendered, allowedHtml);
}

function slugify(value = "") {
  return String(value)
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 96);
}

function validSlug(value) {
  const slug = slugify(value);
  if (!slug || slug !== value) throw new Error(`Invalid content slug: ${value || "(missing)"}`);
  return slug;
}

function safeMediaUrl(value = "") {
  const url = String(value).trim();
  return /^(https?:\/\/|\/)/i.test(url) ? url : "";
}

function isoDate(value, fallback) {
  const date = new Date(value || fallback || Date.now());
  if (Number.isNaN(date.getTime())) return new Date(fallback || Date.now()).toISOString();
  return date.toISOString();
}

function displayDate(value) {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  }).format(new Date(value));
}

function pickItems(payload) {
  if (Array.isArray(payload)) return payload;
  for (const key of ["content", "items", "data", "results"]) {
    if (Array.isArray(payload?.[key])) return payload[key];
  }
  throw new Error("Content Engine response did not include a content array");
}

export function normalizePublishedItems(payload) {
  return pickItems(payload)
    .filter((item) => item?.status === "published")
    .filter((item) => !item.property && !item.propertySlug || (item.property ?? item.propertySlug) === PROPERTY_SLUG)
    .map((item) => {
      const slug = validSlug(item.slug || slugify(item.title));
      const publishedAt = isoDate(item.publishedAt ?? item.published_at ?? item.createdAt);
      const updatedAt = isoDate(item.updatedAt ?? item.updated_at ?? item.modifiedAt, publishedAt);
      const excerpt = String(item.excerpt || item.metaDescription || "").trim();
      const title = String(item.title || "").trim();
      const body = String(item.body ?? item.markdown ?? item.content ?? "").trim();
      if (!title || !excerpt || !body) throw new Error(`Published item "${slug}" is missing title, excerpt, or body`);
      return {
        slug,
        title,
        excerpt,
        body,
        publishedAt,
        updatedAt,
        seoTitle: String(item.seoTitle ?? item.metaTitle ?? item.seo?.title ?? title).trim(),
        seoDescription: String(item.seoDescription ?? item.metaDescription ?? item.seo?.description ?? excerpt).trim(),
        ogTitle: String(item.socialMeta?.ogTitle ?? item.ogTitle ?? item.seoTitle ?? item.metaTitle ?? title).trim(),
        ogDescription: String(item.socialMeta?.ogDescription ?? item.ogDescription ?? item.seoDescription ?? item.metaDescription ?? excerpt).trim(),
        heroImageUrl: safeMediaUrl(item.heroImageUrl ?? item.heroImage?.url ?? item.ogImage ?? item.socialMeta?.ogImage),
        heroImageAlt: String(item.heroImageAlt ?? item.heroImage?.alt ?? "").trim(),
      };
    })
    .sort((a, b) => new Date(b.publishedAt) - new Date(a.publishedAt));
}

function jsonLd(value) {
  return JSON.stringify(value).replaceAll("<", "\\u003c");
}

function siteChrome(template) {
  const header = template.match(/<body>[\s\S]*?(<header class="site-header">[\s\S]*?<\/header>)/i)?.[1];
  const footer = template.match(/(<footer class="site-footer">[\s\S]*?<\/footer>)/i)?.[1];
  if (!header || !footer) throw new Error("Could not extract the shared header and footer from resources/index.html");
  return { header, footer };
}

function documentShell({ title, description, canonical, ogType, ogImage, structuredData, header, footer, main }) {
  const imageMeta = ogImage ? `\n    <meta property="og:image" content="${escapeHtml(ogImage)}">` : "";
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(description)}">
    <link rel="canonical" href="${escapeHtml(canonical)}">
    <meta property="og:title" content="${escapeHtml(title)}">
    <meta property="og:description" content="${escapeHtml(description)}">
    <meta property="og:type" content="${escapeHtml(ogType)}">
    <meta property="og:url" content="${escapeHtml(canonical)}">${imageMeta}
    <meta name="twitter:card" content="${ogImage ? "summary_large_image" : "summary"}">
    <link rel="icon" href="/assets/brand/icon.png" type="image/png">
    <link rel="stylesheet" href="/assets/css/styles.css?v=20260721content1">
    <script type="application/ld+json">${jsonLd(structuredData)}</script>
  </head>
  <body>
    ${GENERATED_MARKER}
    <a class="skip-link" href="#main">Skip to content</a>
    ${header}
    ${main}
    ${footer}
    <script src="/assets/js/main.js"></script>
  </body>
</html>
`;
}

function renderIndex(items, chrome) {
  const cards = items.map((item, index) => `
          <article class="content-card">
            <span class="article-number" aria-hidden="true">${String(index + 1).padStart(2, "0")}</span>
            <p class="article-meta"><span>Field notes</span><time datetime="${item.publishedAt}">${displayDate(item.publishedAt)}</time></p>
            <h2><a href="/content/${item.slug}/">${escapeHtml(item.title)}</a></h2>
            <p>${escapeHtml(item.excerpt)}</p>
            <a class="story-link" href="/content/${item.slug}/">Read article <span aria-hidden="true">→</span></a>
          </article>`).join("");
  const main = `<main id="main">
      <section class="content-index-hero"><div class="container"><p class="eyebrow">Herzen Co. content</p><h1>Field notes for building and leading products.</h1><p>Practical articles from the Herzen Content Engine, published only after review.</p></div></section>
      <section class="content-index-list"><div class="container"><div class="content-grid">${cards || "<p>No articles have been published yet.</p>"}</div></div></section>
    </main>`;
  return documentShell({
    title: "Product Field Notes and Articles | Herzen Co.",
    description: "Read Herzen Co. articles on product leadership, product delivery, roadmaps, MVP scoping, and building useful software.",
    canonical: `${SITE_URL}/content/`,
    ogType: "website",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: "Herzen Co. Content",
      url: `${SITE_URL}/content/`,
      hasPart: items.map((item) => ({ "@type": "Article", headline: item.title, url: `${SITE_URL}/content/${item.slug}/` })),
    },
    ...chrome,
    main,
  });
}

function renderArticle(item, chrome) {
  const canonical = `${SITE_URL}/content/${item.slug}/`;
  const hero = item.heroImageUrl
    ? `<figure class="content-hero-image"><img src="${escapeHtml(item.heroImageUrl)}" alt="${escapeHtml(item.heroImageAlt || item.title)}"></figure>`
    : "";
  const main = `<main id="main">
      <article class="content-article">
        <header class="content-article-header"><div class="container container-narrow"><p class="eyebrow">Herzen Co. field notes</p><h1>${escapeHtml(item.title)}</h1><p class="content-excerpt">${escapeHtml(item.excerpt)}</p><div class="content-dates"><span>Published <time datetime="${item.publishedAt}">${displayDate(item.publishedAt)}</time></span><span>Updated <time datetime="${item.updatedAt}">${displayDate(item.updatedAt)}</time></span></div></div></header>
        <div class="container container-narrow">${hero}<div class="prose">${sanitizeMarkdown(item.body)}</div><footer class="content-article-footer"><a class="story-link" href="/content/">← All field notes</a></footer></div>
      </article>
    </main>`;
  return documentShell({
    title: item.seoTitle,
    description: item.seoDescription,
    canonical,
    ogType: "article",
    ogImage: item.heroImageUrl,
    structuredData: {
      "@context": "https://schema.org",
      "@type": "Article",
      headline: item.title,
      description: item.seoDescription,
      datePublished: item.publishedAt,
      dateModified: item.updatedAt,
      mainEntityOfPage: canonical,
      url: canonical,
      ...(item.heroImageUrl ? { image: item.heroImageUrl } : {}),
      publisher: { "@type": "Organization", name: "Herzen Co.", url: SITE_URL },
    },
    ...chrome,
    main,
  });
}

export function updateSitemapXml(xml, items) {
  const withoutGenerated = xml.replace(/\s*<url><loc>https:\/\/herzenco\.com\/content\/[^<]*<\/loc>[\s\S]*?<\/url>/g, "");
  const entries = [
    { url: `${SITE_URL}/content/`, lastmod: items[0]?.updatedAt ?? new Date().toISOString() },
    ...items.map((item) => ({ url: `${SITE_URL}/content/${item.slug}/`, lastmod: item.updatedAt })),
  ].map(({ url, lastmod }) => `  <url><loc>${escapeXml(url)}</loc><lastmod>${String(lastmod).slice(0, 10)}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>`).join("\n");
  return withoutGenerated.replace(/\s*<\/urlset>\s*$/, `\n${entries}\n</urlset>\n`);
}

export async function fetchPublishedContent({ contentEngineUrl, fetchImpl = fetch }) {
  if (!contentEngineUrl) throw new Error("CONTENT_ENGINE_URL is required");
  const endpoint = new URL("/api/content", contentEngineUrl);
  endpoint.searchParams.set("property", PROPERTY_SLUG);
  endpoint.searchParams.set("status", "published");
  const response = await fetchImpl(endpoint, { headers: { accept: "application/json" } });
  if (!response.ok) throw new Error(`Content Engine request failed (${response.status} ${response.statusText})`);
  return normalizePublishedItems(await response.json());
}

export async function generateContent({ rootDir = process.cwd(), items }) {
  const resourcesTemplate = await fs.readFile(path.join(rootDir, "resources/index.html"), "utf8");
  const chrome = siteChrome(resourcesTemplate);
  const contentDir = path.join(rootDir, "content");
  await fs.rm(contentDir, { recursive: true, force: true });
  await fs.mkdir(contentDir, { recursive: true });
  await fs.writeFile(path.join(contentDir, "index.html"), renderIndex(items, chrome));
  for (const item of items) {
    const articleDir = path.join(contentDir, item.slug);
    await fs.mkdir(articleDir, { recursive: true });
    await fs.writeFile(path.join(articleDir, "index.html"), renderArticle(item, chrome));
  }
  const sitemapPath = path.join(rootDir, "sitemap.xml");
  const sitemap = await fs.readFile(sitemapPath, "utf8");
  await fs.writeFile(sitemapPath, updateSitemapXml(sitemap, items));
}

export async function syncContent(options = {}) {
  const items = await fetchPublishedContent({
    contentEngineUrl: options.contentEngineUrl ?? process.env.CONTENT_ENGINE_URL,
    fetchImpl: options.fetchImpl,
  });
  await generateContent({ rootDir: options.rootDir, items });
  return items;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  syncContent()
    .then((items) => console.log(`Generated ${items.length} published article(s).`))
    .catch((error) => {
      console.error(`Content sync failed: ${error.message}`);
      process.exitCode = 1;
    });
}
